SELECT 'Hello from DBTICKETS.sql' FROM SYSIBM.DUAL;

CREATE TABLE DBTICKETS
 (NUMTICKET    VARCHAR(9)     NOT NULL,
  DESCRIPTION  VARCHAR(100) NOT NULL,
  EVENTDATE    TIMESTAMP,
  PRIMARY KEY(NUMTICKET));

  